# Generated by Django 3.1.4 on 2020-12-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepost',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
